#!/usr/bin/env node
/**
 * HTML 预压缩脚本
 * 在构建完成后压缩所有 HTML 文件
 */

import { minify } from 'html-minifier-terser';
import { glob } from 'glob';
import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';

const DIST_DIR = resolve(process.cwd(), 'dist');

async function compressHTML() {
  console.log('🗜️  开始压缩 HTML 文件...\n');
  
  try {
    // 查找所有 HTML 文件
    const files = await glob('**/*.html', { cwd: DIST_DIR, absolute: true });
    
    if (files.length === 0) {
      console.log('⚠️  未找到 HTML 文件');
      return;
    }
    
    console.log(`📁 找到 ${files.length} 个 HTML 文件\n`);
    
    let totalOriginal = 0;
    let totalCompressed = 0;
    
    for (const file of files) {
      const content = await readFile(file, 'utf-8');
      const originalSize = Buffer.byteLength(content, 'utf-8');
      
      const minified = await minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        conservativeCollapse: false,
        decodeEntities: true,
        html5: true,
        includeAutoGeneratedTags: false,
        minifyCSS: true,
        minifyJS: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeOptionalTags: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
      });
      
      const compressedSize = Buffer.byteLength(minified, 'utf-8');
      const savings = originalSize - compressedSize;
      const savingsPercent = ((savings / originalSize) * 100).toFixed(1);
      
      await writeFile(file, minified);
      
      totalOriginal += originalSize;
      totalCompressed += compressedSize;
      
      const relativePath = file.replace(DIST_DIR, '');
      console.log(`✅ ${relativePath}`);
      console.log(`   ${formatBytes(originalSize)} → ${formatBytes(compressedSize)} (${savingsPercent}% 减少)\n`);
    }
    
    const totalSavings = totalOriginal - totalCompressed;
    const totalSavingsPercent = ((totalSavings / totalOriginal) * 100).toFixed(1);
    
    console.log('📊 压缩统计');
    console.log('═══════════════════════════════════════');
    console.log(`总原始大小: ${formatBytes(totalOriginal)}`);
    console.log(`总压缩大小: ${formatBytes(totalCompressed)}`);
    console.log(`节省空间:   ${formatBytes(totalSavings)} (${totalSavingsPercent}%)`);
    console.log('═══════════════════════════════════════');
    
  } catch (error) {
    console.error('❌ 压缩失败:', error);
    process.exit(1);
  }
}

function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

compressHTML();
